apiVersion: apps/v1
kind: Deployment
metadata: 
  name: demo-deployment
  labels:
    apps: demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-deployment
  template: 
    metadata:
      name: demo-deployment
      namespace: default
      labels:
        app: demo-deployment
    spec:
      containers:
        - name: demo-deployment
          image: saisatyateja/studentcourserestapi:1.0
          envFrom:
            - configMapRef:
                name: demo-configmap-1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
          readinessProbe:
            httpGet:
              port: 8080
          resources:
            requests:
              cpu: "1000m"
              memory: "300Mi"
            limits:
              cpu: "1500m"
              memory: "600Mi"
          